Update send-emails

diff --git a/bin/send-emails b/bin/send-emails
--- a/bin/send-emails
+++ b/bin/send-emails
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+set -e # exit on error
+set -u # exit on undefined variable
+set -o pipefail # exit on error in pipe
+shopt -s nullglob # expand empty globs to nothing, not to itself
+
 readonly USAGE="
 
 USAGE:
@@ -33,17 +38,15 @@ from_directory="$2"
 
 
 if [[ ! -d "$from_directory" ]]; then
-    echo "ERROR: directory '$from_directory' does not exist"
+    echo "ERROR: directory '$from_directory' does not exist" 1>&2
     exit 1
 fi
 
-for mailfile in $from_directory/*.eml; do
-    printf "\n\n"
-    to_email=$(basename ${mailfile%.eml})
-    printf "sending $mailfile to $to_email\n"
-    printf -- "--------------------------\n"
+for mailfile in "$from_directory"/*.eml; do
+    to_email=$(basename "${mailfile%.eml}")
+    printf "sending %s to %s\n" "$mailfile"  "$to_email"
     #cat $mailfile | mutt -s "subject" -- $email
-    # prefer sendmail, because then also subject and recipient in mailfile
-    sendmail -t -i -f $from_email <$mailfile
-    sleep $SLEEP_BETWEEN_SENDING_EMAILS # not to overflow mail server
+    # prefer sendmail, because then also subject and recipient in mailfile which gives the ability to setup a more complete email in a file earlier
+    sendmail -t -i -f "$from_email" <"$mailfile"
+    sleep "$SLEEP_BETWEEN_SENDING_EMAILS" # not to overflow mail server
 done
